openapi: 3.0.3
info:
  title: TODO API
  description: シンプルなTODOリスト管理API
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: ローカル開発環境
  - url: https://my-app.railway.app
    description: 本番環境

tags:
  - name: todos
    description: TODO操作
  - name: health
    description: ヘルスチェック

paths:
  /health:
    get:
      tags:
        - health
      summary: ヘルスチェック
      operationId: getHealth
      responses:
        '200':
          description: 正常
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /todos:
    get:
      tags:
        - todos
      summary: TODO一覧取得
      operationId: getTodos
      responses:
        '200':
          description: TODO一覧の取得に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoListResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: "OK"
    
    Todo:
      type: object
      required:
        - id
        - title
        - completed
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          maxLength: 255
          example: "買い物に行く"
        completed:
          type: boolean
          example: false

    TodoListResponse:
      type: object
      required:
        - todos
      properties:
        todos:
          type: array
          items:
            $ref: "#/components/schemas/Todo"
